cnip/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace='cnip')),

]

user/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf.urls import url

from . import views

app_name = 'user'

urlpatterns = [
    path('', TemplateView.as_view(template_name='cnip/landing_cnip.html'), name='cnip'),
    path('ok/', TemplateView.as_view(template_name='cnip/ok.html'), name='ok'),
    path('about/', TemplateView.as_view(template_name='cnip/about.html'), name='about'),
    path('question/', views.QuestionView.as_view(template_name='cnip/question.html'), name='question'),
    url(r'^service/$', views.ServiceListView.as_view(), name='service'),
    url(r'^service/(?P<pk>\d+)$', views.ServiceDetailView.as_view(), name='detail'),
    # path('service/', views.ListServiceView.as_view(template_name='cnip/list_service.html'), name='service'),
    path('service/id1', views.ListServiceViewId1.as_view(template_name='cnip/list_service_id_1.html')),
    path('service/id2', views.ListServiceViewId2.as_view(template_name='cnip/list_service_id_2.html')),
    path('service/id3', views.ListServiceViewId3.as_view(template_name='cnip/list_service_id_3.html')),
    path('service/id4', views.ListServiceViewId4.as_view(template_name='cnip/list_service_id_4.html')),
    path('service/id5', views.ListServiceViewId5.as_view(template_name='cnip/list_service_id_5.html')),
    path('service/id6', views.ListServiceViewId6.as_view(template_name='cnip/list_service_id_6.html')),

]

user/models.py
from django.conf import settings
from django.db import models
# from django.core.urlresolvers import reverse
from django.urls import reverse


# Create your models here.

class User(models.Model):
    fist_name = models.CharField(max_length=64, verbose_name='Імʼя')
    last_name = models.CharField(max_length=64, verbose_name='Призвище')
    email = models.EmailField(max_length=128, verbose_name='Електронна почта')
    phone_number = models.CharField(max_length=64, verbose_name='Номер телефона')
    #
    # def __str__(self):
    #     return f'{self.fist_name} {self.last_name}'


class Question(models.Model):
    fist_name = models.CharField(max_length=64, verbose_name='Імʼя', null=True, blank=True)
    last_name = models.CharField(max_length=64, verbose_name='Призвище', null=True, blank=True)
    phone_number = models.CharField(max_length=64, verbose_name='Номер телефона', null=True, blank=True)
    email = models.EmailField(max_length=128, verbose_name='Електронна адреса', null=True, blank=True)
    question = models.TextField(verbose_name='Питання', null=True, blank=True)

    def __str__(self):
        return f'{self.last_name}'

    class Meta:
        verbose_name = 'Питання'
        verbose_name_plural = 'Питання'


class Service(models.Model):
    service = models.CharField('Назва категорії', max_length=64, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, null=True, blank=True)

    def __str__(self):
        return f'{self.service}'

    class Meta:
        verbose_name = 'Категорія послуг'
        verbose_name_plural = 'Категорії послуг'
        ordering = ['service']


class ListService(models.Model):
    category = models.ForeignKey(Service, null=True, on_delete=models.PROTECT, verbose_name='Категорія послуг')
    title = models.CharField('Назва послуги', max_length=128)
    price = models.DecimalField('Вартість', max_digits=10, decimal_places=2, null=True)
    content = models.TextField('Опис', null=True, blank=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, null=True, blank=True)
    comment = models.CharField('Коментар', max_length=200, null=True, blank=True)

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Найменування послуги'
        verbose_name_plural = 'Найменування послуг'

user/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from urllib3 import request

from .form import SubscriberForm, QuestionForm
from .models import User, Question, ListService, Service
from django.views.generic.list import ListView


# Create your views here.

# class SubscriberView(FormView):
#     model = User
#     form_class = SubscriberForm
#     template_name = 'cnip/landing_cnip.html'
#     success_url = reverse_lazy('user:ok')
#
#     def form_valid(self, form):
#         form.save()
#         return super().form_valid(form)


# def user_list(request):
#     return render(request, 'cnip/landing_cnip.html', {})

class QuestionView(FormView):
    model = Question
    form_class = QuestionForm
    template_name = 'cnip/question.html'
    success_url = ('http://127.0.0.1:8000/cnip/ok/')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


"""отображение услуг по категориям"""


class ServiceListView(ListView):
    model = ListService

    def get_context_data(self, **kwargs):
        context = super(ServiceListView, self).get_context_data(**kwargs)
        context['category_list'] = Service.objects.all()
        return context


class ServiceDetailView(DetailView):
    model = ListService


class ListServiceViewId1(ListView):
    model = ListService

    def get_queryset(self):
        return ListService.objects.filter(category__id='1')


class ListServiceViewId2(ListView):
    model = ListService

    def get_queryset(self):
        return ListService.objects.filter(category__id='2')


class ListServiceViewId3(ListView):
    model = ListService

    def get_queryset(self):
        return ListService.objects.filter(category__id='3')


class ListServiceViewId4(ListView):
    model = ListService

    def get_queryset(self):
        return ListService.objects.filter(category__id='4')


class ListServiceViewId5(ListView):
    model = ListService

    def get_queryset(self):
        return ListService.objects.filter(category__id='5')


class ListServiceViewId6(ListView):
    model = ListService

    def get_queryset(self):
        return ListService.objects.filter(category__id='6')

templates/cnip/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>О нас</title>
</head>
<body>
<h1>About</h1>
</body>
</html>

templates/cnip/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>ЦНИП</title>
    <style>

        html {
            position:relative;
            min-height:100%;
        }

        body {
            padding:0 0 60px 0;
            background-color: #FFFFE0
        }

        footer {
            position:absolute;
            bottom:0;
            left:0;
            padding:20px 0;
            width:100%;}

    </style>

</head>
<body>
<div class="container">
<!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'user:cnip' %}">Центр надання юридичних послуг</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="about/">О нас</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://127.0.0.1:8000/cnip/service/">Услуги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Контракти</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Portfolio
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                            <a class="dropdown-item" href="portfolio-1-col.html">1 Column Portfolio</a>
                            <a class="dropdown-item" href="portfolio-2-col.html">2 Column Portfolio</a>
                            <a class="dropdown-item" href="portfolio-3-col.html">3 Column Portfolio</a>
                            <a class="dropdown-item" href="portfolio-4-col.html">4 Column Portfolio</a>
                            <a class="dropdown-item" href="portfolio-item.html">Single Portfolio Item</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Blog
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                            <a class="dropdown-item" href="blog-home-1.html">Blog Home 1</a>
                            <a class="dropdown-item" href="blog-home-2.html">Blog Home 2</a>
                            <a class="dropdown-item" href="blog-post.html">Blog Post</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            Other Pages
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                            <a class="dropdown-item" href="full-width.html">Full Width Page</a>
                            <a class="dropdown-item" href="sidebar.html">Sidebar Page</a>
                            <a class="dropdown-item" href="faq.html">FAQ</a>
                            <a class="dropdown-item" href="404.html">404</a>
                            <a class="dropdown-item" href="pricing.html">Pricing Table</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
{% block content %}
{% endblock content %}
<footer class="py-4 bg-dark sticky-bottom>">
    <div class="container">
      <p class="m-0 text-center text-white">м. Запоріжжя, вул. Жуковського, 36</p>
    </div>
</footer>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>



</body>
</html>

templates/cnip/landing_cnip.html
{% extends 'cnip/base.html'%}
{% block content %}
{% load staticfiles %}
<!-- Page Content -->
<style>
    h3 {
        margin-top: 1rem;
        margin-left: 14rem
    }



</style>


<div class="container">
<!-- Heading Row -->
    <div class="row align-items-center my-5">
        <div class="col-lg-6 mt-5">
            <img src="{% static 'img/place_hold.jpg' %}" class="img-fluid rounded mb-4 mb-lg-0"  alt>
        </div>
        <div class="col-lg-6">
            <h1 class="font-weight-light">Business Name or Tagline</h1>
            <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
            <a class="btn btn-primary" href="{% url 'user:question' %}">Отримати консультацію</a>
        </div>
        <h3>Надійна юридична допомога в будь-якій життєвій ситуації</h3>
        <div class="row mt-3">
             <div class="col-md-4 mb-5">
                 <div class="card h-100">
                     <div class="card-body">
                        <h2 class="card-title">Підприємцям</h2>
                          <p class="card-text">Підтримка вашого бізнесу (консультація, підготовка документів, отримання дозвільної документації та представництво інтересів):</p>
                          <ul>
                              <li>податки</li>
                              <li>ліцензії</li>
                              <li>документи</li>
                              <li>юрист на аутсорс</li>
                          </ul>
                     </div>
                     <div class="card-footer">
                        <a href="service/id2" class="btn btn-primary btn-sm">Детальніше</a>
                     </div>
                 </div>
             </div>
      <!-- /.col-md-4 -->
             <div class="col-md-4 mb-5">
                  <div class="card h-100">
                      <div class="card-body">
                          <h2 class="card-title">Іноземцям в Україні</h2>
                          <p class="card-text">Допомога іноземним громадянам в Україні з актуальних правових питань:</p>
                          <ul>
                              <li>оформлення посвідки на проживання, громадянство</li>
                              <li>консультація з сімейних питань</li>
                              <li>допомога підприємцям</li>
                              <li>складання та аналіз договорів</li>
                              <li>інші правові питання</li>
                          </ul>
                      </div>
                      <div class="card-footer">
                          <a href="service/id3" class="btn btn-primary btn-sm">Детальніше</a>
                      </div>
                  </div>
             </div>
      <!-- /.col-md-4 -->
             <div class="col-md-4 mb-5">
                 <div class="card h-100">
                     <div class="card-body">
                          <h2 class="card-title">Сімейний юрист</h2>
                          <p class="card-text">Професійна юридична допомога у вирішенні сімейних питань:</p>
                          <ul>
                              <li>розлучення</li>
                              <li>аліменти</li>
                              <li>спадок</li>
                              <li>майно</li>
                              <li>діти</li>
                          </ul>
                     </div>
                     <div class="card-footer">
                          <a href="service/id4" class="btn btn-primary btn-sm">Детальніше</a>
                     </div>
                 </div>
             </div>
      <!-- /.col-md-4 -->
             <div class="col-md-4 mb-5">
                 <div class="card h-100">
                     <div class="card-body">
                        <h2 class="card-title">Регістраційні послуги</h2>
                          <p class="card-text">Швидкі та якісні регістраційні послуги будь-якого характеру:</p>
                          <ul>
                              <li>підготовка документів для реєстрації юридичних осіб, фізичних осіб підприємців, реєстрація в ЦНАП</li>
                              <li>внесення змін в Статутні документи</li>
                              <li>отримання ліцензій, сертифікатів та іншої дозвільної документації</li>
                              <li>інші послуги</li>
                          </ul>
                     </div>
                     <div class="card-footer">
                        <a href="service/id1" class="btn btn-primary btn-sm">Детальніше</a>
                     </div>
                 </div>
             </div>
      <!-- /.col-md-4 -->
             <div class="col-md-4 mb-5">
                  <div class="card h-100">
                      <div class="card-body">
                          <h2 class="card-title">Послуги адвоката</h2>
                          <p class="card-text">Професійний захист ваших інтересів:</p>
                          <ul>
                              <li>представництво в судах</li>
                              <li>підготовка процесуальних документів</li>
                              <li>стягнення заборгованності</li>
                              <li>cупровід процесу виконання рішення</li>
                              <li>адвокатський запит</li>
                              <li>зберігання документів</li>
                          </ul>
                      </div>
                      <div class="card-footer">
                          <a href="service/id5" class="btn btn-primary btn-sm">Детальніше</a>
                      </div>
                  </div>
             </div>
      <!-- /.col-md-4 -->
             <div class="col-md-4 mb-5">
                 <div class="card h-100">
                     <div class="card-body">
                          <h2 class="card-title">Нерухомість</h2>
                          <p class="card-text">Юридичні послуги у сфері нерухомості та будівництва:</p>
                          <ul>
                              <li>оформлення права власності</li>
                              <li>супроводження угод купівлі-продажу</li>
                              <li>оренда</li>
                              <li>перепланування</li>
                              <li>дозвіл на будівництво</li>
                              <li>виготовлення технічного паспорту</li>
                          </ul>
                     </div>
                     <div class="card-footer">
                          <a href="service/id6" class="btn btn-primary btn-sm">Детальніше</a>
                     </div>
                 </div>
             </div>
         </div>

    </div>
</div>
<!-- Page Content end -->
{% endblock content %}

templates/cnip/list_service.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}
<style>
    #service {
        margin-top: 5.5rem;
    }

</style>


<div class="container" id="service">
    <div class="row">
        <div class="col-lg-3">
            <h3>Категорії послуг</h3>
            <div class="list-group">
                {% for i in object_list %}

                <a href="{% url 'user:name_list'">{{ i.service }}</a>
                {% endfor %}

            </div>

        </div>



        </div>

    </div>
</div>







{% endblock content %}
</html>

templates/cnip/list_service_id_1.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}

<style>

    h3 {
        margin-top: 5rem;
        margin-left: 2rem;
    }

</style>


<h3>Регістраційні послуги</h3>

{% for listservice in object_list %}

<ul>
    <li>{{ listservice.title }} - {{ listservice.price }} грн. </li>
</ul>
{% endfor %}
<a class="btn btn-primary ml-4 mb-5" href="http://127.0.0.1:8000/cnip/question/">Отримати консультацію</a>




{% endblock content %}

templates/cnip/list_service_id_2.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}


{% block content %}

<style>


    h3 {
        margin-top: 5rem;
        margin-left: 2rem;
    }

</style>


<h3>Підприємцям</h3>

{% for listservice in object_list %}

<ul>
    <li>{{ listservice.title }} - {{ listservice.price }} грн. </li>
</ul>
{% endfor %}

<a class="btn btn-primary ml-4 mb-5" href="{% url 'user:question' %}">Отримати консультацію</a>


{% endblock content %}

templates/cnip/list_service_id_3.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}

<style>

    h3 {
        margin-top: 5rem;
        margin-left: 2rem;
    }

</style>


<h3>Іноземцям в Україні</h3>

{% for listservice in object_list %}

<ul>
    <li>{{ listservice.title }} - {{ listservice.price }} грн. </li>
</ul>
{% endfor %}

<a class="btn btn-primary ml-4 mb-5" href="http://127.0.0.1:8000/cnip/question/">Отримати консультацію</a>



{% endblock content %}

templates/cnip/list_service_id_4.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}

<style>

    h3 {
        margin-top: 5rem;
        margin-left: 2rem;
    }

</style>


<h3>Сімейний юрист</h3>

{% for listservice in object_list %}

<ul>
    <li>{{ listservice.title }} - {{ listservice.price }} грн. </li>
</ul>
{% endfor %}

<a class="btn btn-primary ml-4 mb-5" href="http://127.0.0.1:8000/cnip/question/">Отримати консультацію</a>


{% endblock content %}

templates/cnip/list_service_id_5.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}

<style>

    h3 {
        margin-top: 5rem;
        margin-left: 2rem;
    }

</style>


<h3>Послуги адвоката</h3>

{% for listservice in object_list %}

<ul>
    <li>{{ listservice.title }} - {{ listservice.price }} грн. </li>
</ul>
{% endfor %}

<a class="btn btn-primary ml-4 mb-5" href="http://127.0.0.1:8000/cnip/question/">Отримати консультацію</a>


{% endblock content %}

templates/cnip/list_service_id_6.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}

<style>

    h3 {
        margin-top: 5rem;
        margin-left: 2rem;
    }

</style>


<h3>Нерухомість</h3>

{% for listservice in object_list %}

<ul>
    <li>{{ listservice.title }} - {{ listservice.price }} грн. </li>
</ul>
{% endfor %}

<a class="btn btn-primary ml-4 mb-5" href="http://127.0.0.1:8000/cnip/question/">Отримати консультацію</a>


{% endblock content %}

templates/cnip/name_service_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/cnip/ok.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Спасибо за регистрацию</title>
  </head>
  <body>

  </body>
</html>

templates/cnip/question.html
{% extends 'cnip/base.html'%}
{% block content %}

{# Load the tag library #}
{% load bootstrap4 %}

<!--{# Load CSS and JavaScript #}-->
<!--{% bootstrap_css %}-->
<!--{% bootstrap_javascript jquery='full' %}-->

<!--{# Display django.contrib.messages as Bootstrap alerts #}-->
<!--{% bootstrap_messages %}-->

{% load staticfiles %}


<style>
<!--    body {-->
<!--            background-color: #FFFFE0-->
<!--        }-->
    .form-row {
        margin-top: 2rem;
     }


    footer {
        position: absolute;
        bottom: 0;
        width: 100%;
    }
    h4, address {
        margin-top: 5rem;
        margin-left: 5.5rem;

    }





</style>
<h4>Заповніть форму і ми зв'яжемося з вами</h4>
<div class="container">
    <form method="post" class="form-signin"> {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
               {% bootstrap_field form.fist_name size='small' show_label=False placeholder='Ваше імʼя'  %}
            </div>
            <div class="form-group col-md-6">
                {% bootstrap_field form.last_name size='small' show_label=False placeholder='Ваше призвище'  %}
            </div>
             <div class="form-group col-md-6">
                {% bootstrap_field form.phone_number size='small' show_label=False placeholder='Ваш номер телефону'  %}
            </div>
             <div class="form-group col-md-6">
                {% bootstrap_field form.email size='small' show_label=False placeholder='Ваша електронна адреса'  %}
            </div>
             <div class="form-group col-md-6">
<!--                {% bootstrap_label "Ваше питання" %}-->
                {% bootstrap_field form.question show_label=False size='small' placeholder='Введить ваше питання'  %}
            </div>
        </div>
        <button type="submit" class="btn btn-primary mb-3">Відправити</button>
    </form>
</div>








<!--<div class="container">-->
<!--    <form method="post" class="form-signin"> {% csrf_token %}-->
<!--        <div class="form-row">-->
<!--            <div class="form-group col-md-6">-->
<!--                 <label>Ім'я</label>-->
<!--                {{ form.fist_name }}-->
<!--                <input type="text" class="form-control form-control-sm" placeholder="">-->
<!--            </div>-->
<!--            <div class="form-group col-md-6">-->
<!--                 <label>Призвище</label>-->
<!--                 <input type="text" class="form-control form-control-sm" placeholder="">-->
<!--                {{ form.last_name }}-->
<!--            </div>-->
<!--            <div class="form-group col-md-6">-->
<!--                <label>Телефон</label>-->
<!--                 {{ form.phone_number }}-->
<!--                <input type="text" class="form-control form-control-sm" placeholder="">-->
<!--            </div>-->
<!--            <div class="form-group col-md-6">-->
<!--                <label>Електронна почта</label>-->
<!--                {{ form.email }}-->
<!--                <input type="text" class="form-control form-control-sm" placeholder="">-->
<!--            </div>-->
<!--            <div class="form-group col-md-12">-->
<!--                 <label>Питання</label>-->
<!--                {{ form.question }}-->
<!--                <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>-->
<!--            </div>-->
<!--        </div>-->
<!--        <button type="submit" class="btn btn-primary">Відправити</button>-->
<!--    </form>-->
<!--</div>-->



{% endblock content %}

templates/cnip/registration_service_list.html
{% extends 'cnip/base.html'%}
{% block content %}

{# Load the tag library #}
{% load bootstrap4 %}

{% load staticfiles %}





{% endblock content %}

templates/user/listservice_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Спасибо за регистрацию</title>
  </head>
  <body>
        {{ listservice.title }}
  </body>
</html>

templates/user/listservice_list.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}
<style>
    #service {
        margin-top: 5.5rem;
    }

</style>


<div class="container" id="service">
    <div class="row">
        <div class="col-lg-3">
            <h3>Категорії послуг</h3>
            <div class="list-group">
                {% for i in category_list %}

                <a href="{% url 'user:service' %}">{{ i.service }}</a>
                {% endfor %}

            </div>

        </div>



        </div>

    </div>
</div>







{% endblock content %}
</html>

templates/user/service_list.html
{% extends 'cnip/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}

{% block content %}
<style>
    #service {
        margin-top: 5.5rem;
    }

</style>


<div class="container" id="service">
    <div class="row">
        <div class="col-lg-3">
            <h3>Категорії послуг</h3>
            <div class="list-group">
                {% for i in object_list %}

                <a href="{{ i.get_absolute_url }}">{{ i.service }}</a>
                {% endfor %}

            </div>

        </div>



        </div>

    </div>
</div>







{% endblock content %}
</html>